name: fiapeats-ms-produto
services:
  postgres:
    container_name: postgres-ms-produto
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fiapeatsdb
      PGDATA: /var/lib/postgresql/data

    profiles: [database, envfull]
    volumes:
      - vol_postgres_ms_produto_data:/var/lib/postgresql/data
      - ./sqlScripts:/docker-entrypoint-initdb.d

    ports:
      - "5433:5432"
    networks:
      - net-postgres-ms-produto
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-ms-produto
    image: dpage/pgadmin4
    profiles: [database, envfull]
    environment:
      PGADMIN_DEFAULT_EMAIL: dilan_limacampos@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - vol_pgadmin_ms_produto_data:/var/lib/pgadmin

    ports:
      - "5051:80"
    networks:
      - net-postgres-ms-produto

    restart: unless-stopped

  ms-produto-api:
    container_name: api-ms-produto
    build:
      context: .
      args:
        JAR_VERSION: "1.0.25"
      dockerfile: Dockerfile
    profiles: [app, envfull]
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    env_file: "variables/ambient.env"
    networks:
      - net-postgres-ms-produto

networks:
  net-postgres-ms-produto:
    driver: bridge

volumes:
  vol_postgres_ms_produto_data:
  vol_pgadmin_ms_produto_data: