apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fiapeats-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiapeats-api-deployment
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70